### ISSUE TITLE
Feature request: Support changing system app icons if SIP is disabled

### ISSUE THREAD

**Issue by NSExceptional** [tale/iconset#1]

**Comment by tale** [comment]
Yes, this is already on my list!
Additionally, any thoughts to supporting a method with SIP enabled by making a copy of the .app?

**Comment by NSExceptional** [comment]
I guess I don't know how this program works; does it actually modify the app bundle?

Finder is able to change icons for any app without actually modifying the app bundles on disk when you drag an icon file into the app's icon in its Info pane. Is it possible to do whatever Finder is doing?

**Comment by tale** [comment]
This imitates the functionality of what dragging an icon into Finder does. Does the dragging method work with SIP disabled?

**Comment by NSExceptional** [comment]
Gotcha, okay. Yes, it sure does! I think it prompts for a password for system apps though.

**Comment by tale** [comment]
The reason I required iconset to run as sudo is because it asks for a password when doing that with App Store apps too.
I presume Apple must've done some checks to prevent system apps from being themed using the NSWorkspace method. I'll investigate more into other possibilities to see what I can do.

**Comment by tale** [comment]
Ok so upon further investigation, it seems there's a blacklist of apps that aren't allowed to be themed based on entitlements. I'll now attempt to try and discover a way to emulate the icon setting without creating breaking issues.

**Comment by tale** [comment]
Should be addressed with version 0.2!
